version: '3.7'

name: eps-dev

services:
  nginx:
    container_name: eps-core-nginx-web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    environment:
        - DATABASE_URL=sqlite:////data/db.sqlite3
    container_name: eps-core-django-app
    #build: .
    build: .
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
#    command: >
#      sh -c " python manage.py migrate &&
#          gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:5000"       
    volumes:
     - .:/app
     - static_volume:/app/staticfiles
     - sqlitedatavolume:/data
    command: >
      sh -c " python manage.py migrate &&
          gunicorn --bind 0.0.0.0:5000 --config gunicorn-cfg.py core.wsgi"   
#    depends_on:
#     - db
#  db:
#    container_name: core_db
#    image: postgres:12.0-alpine
#    env_file: .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  sqlitedatavolume:
#  postgres_data: