version: '3.7'

name: eps

services:
  nginx:
    container_name: eps-core-nginx-web-deploy
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.deploy.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    environment:
        - DATABASE_URL=sqlite:////data/db.sqlite3
        - SERVER=eps-dev.glotov.net
    container_name: eps-core-django-app-deploy
    image: glotoff/eps:dev
    restart: always
    ports:
      - "5000:5000"  
    volumes:
#     - .:/app
     - static_volume:/app/staticfiles
     - sqlitedatavolume:/data
    command: >
      sh -c " python manage.py migrate &&
          gunicorn --bind 0.0.0.0:5000 --config gunicorn-cfg.py core.wsgi"   

volumes:
  static_volume:
  sqlitedatavolume: