# Generated by Django 4.1.8 on 2023-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
