# Generated by Django 3.2.16 on 2023-04-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230408_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
